[package]
name = "hashgraph-poc"
version = "0.1.0"
authors = ["jaybutera <buterajay@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
rand = "0.6"
